openstreetmap/chef

- cookbooks/planet/files/default/cgi/HEADER.cgi
- cookbooks/planet/files/default/history_cgi/HEADER.cgi
- cookbooks/planet/recipes/default.rb
Update planet description to be more accurate about what the changeset dump is (i.e: it's not changes over the past week), and to include links to the PBF versions of files and the full history dump.
Add the history directory's header information to Chef - previously it was not in any repository.
> Update planet description

- cookbooks/planet/recipes/dump.rb
Version 1.0.1 of planet-dump-ng contains a bug fix which could leave the program in a hung state indefinitely due to poor design of inter-thread communication. Threads finishing would set their index and call the main thread to wake up, but if the main thread didn't wake up before a second thread finished then the first notification would be lost.
> Bump planet-dump-ng version for bug fix.

- cookbooks/planet/files/default/replication-bin/replicate-changesets
This extends the changeset replication code to also include new changeset comments. These are output in the same format as from the XML API call. It's possible that this change might break some parsers, but I'm not sure that anyone is regularly consuming this feed anyway.
> Changeset comments replication

- cookbooks/planet/recipes/dump.rb
- cookbooks/planet/templates/default/planetdump.erb
This bumps the version of `planet-dump-ng` to 1.1.0, the first version capable of dumping changeset comments. The comments are included with the changesets, but for the moment dumped to a separate file called "discussions" while we give anyone who depends on the old format a chance to update their parsers.
> Add changeset comment dumps.

- cookbooks/web/templates/default/logrotate.web.erb
Currently these aren't archived, meaning we can't investigate issues which occurred more than 7 days ago. Nor can we do a long-term historical analysis of the logs to figure out the best values for, e.g: rate limiting parameters.
> Archive cgimap logs to ironbelly.

- cookbooks/planet/templates/default/planetdump.erb
This is the cause of, and fixes zerebubuth/planet-dump-ng#12 - the temporary data for changeset comments dates from February.
I had thought that having the temporaries resumable would make sense, but it seems that it's more confusing to have it keep old data around like that...
> The changeset comments temporary should be cleaned too.

- cookbooks/planet/recipes/dump.rb
Latest version is a small change: default behaviour is now to remove any old data and start from scratch, rather than resuming processing using old data. This seems like saner behaviour.
> Bump planet-dump-ng to latest version.

- cookbooks/planet/recipes/dump.rb
The `planet-dump-ng` program only checks periodically for overflow of the maximum block size allowed by the OSM PBF format. This is too infrequent to catch the 2,000 relations which are >24MB, and the block overflows and causes the process to halt. This work-around just reduces that limit to 500 elements, and has been tested and works for the previous planet. This isn't a real fix, but doing it "properly" (i.e: testing for overflow _before_ each relation is added) is more complex due to rolling back additions to the string table and so forth.
> Bump planet-dump-ng version for work-around.

- roles/exonetric.rb
This'll only apply to Kessie for now, but we'll probably want it for any machine at that site.
> Add local admin for exonetric site.

- cookbooks/planet/files/default/replication-bin/replicate-changesets
Characters in the range `\x01-\x20` except for `\t\n\r` aren't allowed in XML 1.0, so we do the same thing as the planet dump code and replace them with '?'.
> Replace characers which aren't allowed in XML 1.0.

- cookbooks/planet/recipes/dump.rb
Refs https://github.com/zerebubuth/openstreetmap-changeset-replication/issues/3.
> Bump planet dump version to 1.1.3 for char replacement fix.

- cookbooks/planet/files/default/replication-bin/replicate-changesets
Thanks to @pa5cal for pointing this out and filing https://github.com/zerebubuth/openstreetmap-changeset-replication/issues/4.
> Spaces (0x20) should not be replaced, as they are not invalid.

- cookbooks/tilecache/templates/default/logrotate.squid.erb
- cookbooks/tilelog/templates/default/tilelog.erb
Take yesterday's squid logs for analysis rather than two days ago.
@Firefishy - I think there was a reason why we were taking 2 days ago, but I can't figure it out now. Seems to me that this would work okay, as the logs should be rotated at 0625, compressed and uploaded, then the analysis will run at 1722. Ten hours to compress and upload should be enough, right?
> Reduce tile log analysis delay.

- cookbooks/planet/recipes/dump.rb
Version 1.1.3 of `planet-dump-ng` was not able to handle text fields greater than 64kB in length. Previously, this hadn't been a problem but [changeset 39766630](http://www.openstreetmap.org/changeset/39766630) has a comment 95kB in length.
Version 1.1.4 of `planet-dump-ng` fixes this, and it should now be able to support much larger comments.
> Bump version of planet-dump-ng to get fixes for long changeset comments.

- .gitignore
- .kitchen.yml
- Gemfile
- Gemfile.lock
This initial configuration uses kitchen-vagrant to test the tools cookbook.
I tried, and failed^Whaven't yet succeeded in getting more complex cookbooks to run, so I fell back on a pretty simple cookbook. Even then, there were challenges getting it to work with kitchen-docker, so I stuck with kitchen-vagrant for now.
The choice of a global test-kitchen setup vs a per-cookbook setup is not my first preference. Unfortunately there's no straightforward way to implement anything else, given our mono-repo and not using any cookbook publication systems. Using a global test-kitchen config is also the result that @zerebubuth came up with independently during work in June.
> Add test-kitchen

- cookbooks/tilecache/templates/default/squid.conf.erb
These are currently 7% of total usage between them:
1. User-Agent `Mozilla/5.0 (Windows NT 5.1)` is not a real browser.
2. User-Agent `osmdroid` is a library, but the app should set this to an specific identifiable value.
3. When no User-Agent or referer is set.
> Block tile abusers.

- cookbooks/tilecache/templates/default/squid.conf.erb
The extra load appears to be a major contributory factor to slow tile loading and the general melting of tile servers.
The owner of the site was contacted a short time ago, probably not long enough to have reacted yet. The site is definitely in violation of the [acceptable use policy](http://wiki.openstreetmap.org/wiki/Tile_usage_policy).
The question is; should we go ahead with the block immediately, or give some grace period?
> Block fastpokemap, currently 13% of tile usage.

- cookbooks/planet/files/default/replication-bin/replicate-changesets
More explicit syncing, and sync the directories too. This attempts to avoid more data loss and empty files. Also adds an individual state file for each replication file.
This might be overkill, but I'm getting pretty tired of this problem coming back every time ironbelly crashes.
> More explicit syncing, and sync the directories too.

- cookbooks/planet/files/default/replication-bin/replicate-changesets
Split up large method to make rubocop happy, and fix a typo.
> Make rubocop happy, and fix typo.

- cookbooks/web/templates/default/apache.backend.erb
The [Apache docs](https://httpd.apache.org/docs/2.4/mod/core.html#cgipassauth) say that this option is needed for `mod_proxy_fcgi` to pass "Authorization" to FCGI processes. CGImap needs to access this header in order to figure out if a request has a valid OAuth header.
> Pass authorisation headers to cgimap so that it can handle OAuth.

- cookbooks/hardware/recipes/default.rb
Add lldp daemon to get Link Layer Discovery Protocol (LLDP) announcements from switch and send LLDP announcements to switch.
lldpcli show neighbors # show switch port + details
lldpcli show chassis # show details sent to switch
> Add lldpd support

- cookbooks/munin/files/default/rrddump.sh
- cookbooks/munin/templates/default/rrddump.cron.erb
* Touch XML files to reflect date of original RRD file.
* Don't run dump in parallel.
* Only keep latest 3 files, delete older ones.
> Fixes to munin dump functionality

- cookbooks/tile/templates/default/replicate.erb
#685 would change the default behavior of osm2pgsql. It may be a long time before this change makes it through osm2pgsql release, Debian packaging, Ubuntu packaging, and Ubuntu LTS release, but best practice is to specify the database name anyways.
> Specify database for osm2pgsql on rendering servers

- cookbooks/tile/templates/default/expire-tiles.erb
- cookbooks/tile/templates/default/replicate.erb
This can matter on more recent versions of osm2pgsql where type detection is done by filename. The `find` cleanup line later on gets both osm and osc files, so no changes are needed there.
> Use .osc.gz for diffs that tile replication fetches

- cookbooks/hardware/recipes/default.rb
Add the mcelog daemon to log machine check events.
The Corrected Error (CE) ECC events are useful. The daemon by default attempts to "Offline" memory which has repeated CE errors.
We should likely add some custom alerting via `/etc/mcelog/[error type]-trigger.local` scripts
> Add mcelog daemon

- Gemfile.lock
12.2.0 has a pretty nasty regression where it alerted on any resource
that had an action named :create, which was not the intention
Signed-off-by: Tim Smith <tsmith@chef.io>
> Use Foodcritic 12.2.1

- cookbooks/planet/recipes/default.rb
- cookbooks/planet/templates/default/old-planet-file-cleanup.cron.erb
- cookbooks/planet/templates/default/old-planet-file-cleanup.erb
At the moment it's just hard-coded to the general consensus view in https://github.com/openstreetmap/operations/issues/180 that we should keep the last 4 weeks of planet files, and the first planet for each calendar month before that.
This doesn't touch any of the "historical interest" planets in `/store/planet/cc-by-sa`.
Let me know if there are other dates that we have special reasons for wanting to keep, and I'll whitelist them.
> Add cron job to delete old planet files.

- cookbooks/planet/templates/default/old-planet-file-cleanup.cron.erb
Not every Monday and additionally the 1st through 7th, as the previous cron configuration actually meant. Turns out the command runs when either the day of week matches _or_ the day of month matches, unlike all the other rules.
This fixes it to only run on the 1st Monday of the month by filtering the invocations, as suggested by the example in the `crontab(5)` man page.
> Run old planet file cleanup on first Monday of the month.

- cookbooks/planet/recipes/dump.rb
Version 1.1.6 includes a [fix for the table header parser](https://github.com/zerebubuth/planet-dump-ng/commit/89e8567a025d4bd88cfeaa62ac962721c6b81fb4) to allow explicit public schemas, which started getting added to the dumps as part of the upstream [PostgreSQL fix for CVE-2018-1058](https://wiki.postgresql.org/wiki/A_Guide_to_CVE-2018-1058:_Protect_Your_Search_Path).
> Bump planet-dump-ng version to v1.1.6.

- cookbooks/planet/templates/default/old-planet-file-cleanup.cron.erb
- cookbooks/planet/templates/default/old-planet-file-cleanup.erb
Enable the old planet file cleanup on ironbelly and grisu by removing the `--dry-run` flag from the script.
It has been running as expected, except for a typo which meant it wasn't cleaning up old XML full history planet files. That's fixed below.
If you're happy with this, and we merge it, then I'll run it by hand once and again in `--dry-run`, just to make doubly sure that it's doing what it's supposed to in-situ. (I already tested this locally, but always worth being careful!)
> Enable old planet file cleanup

- cookbooks/planet/files/default/cgi/HEADER.cgi
Fix link to  https://wiki.openstreetmap.org/wiki/Planet.osm#Processing_the_file . Somebody fiddled with... I mean...  corrected the heading per the [wiki conventions](https://wiki.openstreetmap.org/wiki/Wiki_guidelines#Titles_-_Page_naming_convention), which meant this anchor link stopped working.
> Fix anchor link capitalisation Processing_the_file

- cookbooks/cgiirc/templates/default/cgiirc.config.erb
Add "#osm-cwg" to the channel drop-down appearing on https://irc.openstreetmap.org .
This is the IRC channel we use for Communication Working Group meetings, and between-meeting coordination. There was some [discussion of this idea in CWG meetings](https://wiki.osmfoundation.org/wiki/CWG_meeting_2018-04-12). I think it originated from a desire to be more inviting, encouraging people to join our working group or just visit our meetings.
> Add #osm-cwg to irc.osm.org drop-down

- roles/viserion.rb
Ram increased  from 24 GB -> 48 GB
cache_mem => "12500 MB" increased  to cache_mem => "35000 MB"
Hope those are OK values.
> Increase cache memory for viserion

- cookbooks/wiki/templates/default/mw-ext-Wikibase.inc.php.erb
This feature will become available in v1.33. For now,
we continue using a nasty hack that should be removed as soon as
we migrate.
The current nasty hack:
$wgResourceModules['wikibase.ui.entitysearch']['scripts'] = [];
Until then, it's a noop.
> Added support for enableEntitySearchUI

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
This changes a setting in MediaWiki, so that the system resolves double redirects (redirections to redirections to wiki pages) automatically. 
MediaWiki handbook entry: https://www.mediawiki.org/wiki/Help:Redirects#Double_redirects
Discussion with a wiki admin about potential downsides of this: https://wiki.openstreetmap.org/wiki/User_talk:Lyx#Automatic_double_redirect_resolution
<s>In addition, a reference to a non-functional web site is removed. </s>
> automatic double redirect resolution for the Wiki

- cookbooks/mediawiki/templates/default/apache.erb
These redirects allow proper Wikidata Query Service linking,
same as implemented on WMF sites.
> Add Apache redirects for wiki

- cookbooks/ftp/recipes/default.rb
- cookbooks/networking/definitions/firewall_rule.rb
- cookbooks/networking/templates/default/shorewall-rules.erb
Adds helper support to firewall_rule.
Enable netfilter FTP helper for ftp cookbook.
> Add firewall_rule helper support

- cookbooks/web/resources/rails_port.rb
I plan to change the default for `trace_use_job_queue` to `true` in upstream, so that new deployments work out-of-the-box (and also make it easier for developers to use locally). However, it's not quite ready for prime-time on osm.org so we still want to use the external importer for now.
I've followed the existing example for other options in this file, but please note that I haven't tested running this cookbook since we don't have test-kitchen set up for it yet.
> Set trace_use_job_queue explicitly

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
The wiki currently sends out e-mails for e-mail address confirmation containing http links. This change intends to make Mediawiki use https instead. 
Relevant manual page: https://www.mediawiki.org/wiki/Manual:$wgCanonicalServer
This fixes https://trac.openstreetmap.org/ticket/5466.
> Set $wgCanonicalServer to change links in confirmation emails to https

- cookbooks/civicrm/attributes/default.rb
Version bump:
* Handle more names through urlescape
* Validate names on public signup form
> CiviCRM osm username extension update

- cookbooks/dmca/files/default/html/index.php
This replaces the URL with the correct one (https://wiki.osmfoundation.org/wiki/Licence_and_Legal_FAQ/Takedown_procedure/When_To_Use_The_Form)
> Link to explanantions when not to use the form is 3-fold redirect

- cookbooks/mediawiki/resources/site.rb
- cookbooks/mediawiki/templates/default/mw-ext-Interwiki.inc.php.erb
Assigns ```interwiki``` permission to sysops, so they can modify the interwiki table. 
I suggested this change when we were discussing about renaming the project namespace to ```Wiki```. I think removing the interwiki link with this prefix is a prerequisite. 
Link to the discussion: https://wiki.openstreetmap.org/w/index.php?title=Talk:Wiki&diff=prev&oldid=1844371
Link to MediaWiki docs: https://www.mediawiki.org/wiki/Extension:Interwiki#Installation
Closes openstreetmap/operations#296.
> Allow sysops to modify interwiki table

- cookbooks/mediawiki/templates/default/mw-ext-Interwiki.inc.php.erb
In #232, I unintentionally removed the interwiki extension. Sorry, I misunderstood Chef! Nothing bad happened, the permission to modify the interwikis is just pretty useless if the extension is missing ;-).
> Re-add interwiki extension (accidentally removed previously)

- cookbooks/wiki/recipes/default.rb
The current name of the project/meta namespace was considered confusing, because the pages in this namespace contain organisational content about the wiki (see https://wiki.openstreetmap.org/wiki/OpenStreetMap:VisualEditor for instance), the name ```OpenStreetMap``` implied however some relevance for OSM itself. 
Renaming was discussed at https://wiki.openstreetmap.org/w/index.php?title=Talk:Wiki&oldid=1846962#Renaming_the_project_name_space
I already carried out some manual fixing to avoid breaking links and I will check again after renaming.
> Rename meta namespace in main wiki

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
the new version moved UI-editing rights out of sysop and its own group because large wikis may have too big of a non-techy admin community (thousands). It would be pointless for a small wiki like ours.
> after MW upgrade sysops unable to edit MW UI

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
another issues with the new way gadgets are being used - need an extra right for sysops explicitly declared.
> enable gadgets-edit rights to sysops

- cookbooks/apt/templates/default/sources.list.erb
Ubuntu 18.04 default install no longer enabled `apt-src` sources.
* Improves `apt-get update` speed
* Minor CI performance importment.
> apt: Disable used apt-src per Ubuntu 18.04 default

- cookbooks/blogs/recipes/default.rb
- cookbooks/blogs/templates/default/cron.erb
Switch to using safe `bundle install --deployment` instead of
global install, which may conflict with other dependencies.
> blogs: use bundle install deployment over global

- cookbooks/supybot/templates/default/git.conf.erb
We merged gravitystorm/openstreetmap-carto#4032, so this branch is no longer needed.
> Remove schema_changes from irc bot

- cookbooks/git/templates/default/apache.erb
Effectively a dummy commit to test Git Actions when git.openstreetmap.org has an MTU 1400.
> git: tweak description for apache keepalive timeout

- cookbooks/tilecache/templates/default/nginx_tile.conf.erb
`okhttp/` is a default user-agent and prohibited by the usage policy.
I can't identify what `Android` refers to. It doesn't match Android UAs I've seen, but it's either a faked UA or a generic UA I can't identify.
The two apps are from https://github.com/openstreetmap/operations/issues/371 and do not have attribution.
Not locally tested.
> Block some heavy apps and default user-agents

- cookbooks/tilecache/templates/default/nginx_tile.conf.erb
Untested - could use double-checking for the right escaping on C# TilesDownloader
> Block more library defaults from tiles

- cookbooks/tilecache/templates/default/nginx_tile.conf.erb
These apps were contacted about moving to a different tile service and did not reply.
> Block some taxi apps

- .github/workflows/test-kitchen.yml
- .kitchen.yml
- cookbooks/mediawiki/resources/site.rb
- test/data_bags/accounts/wiki.json
- test/data_bags/wiki/passwords.json
- Updated Ubuntu from 16.04 to 18.04 based on [current running hardware](https://hardware.openstreetmap.org)
- ~~Added Mediwaiki Apt repository to support Parsoid install~~ Added `apt` as `mediawiki` dependency to complete installation
- ~~Added missing Wiki user account~~ Added `accounts` as `mediawiki` dependency to complete installation
- Added dummy passwords in test data bag
Test plan:
---
1. Add test kitchen configuration like:
- name: migurski_testing
run_list:
- recipe[munin]
- recipe[wiki]
- role[wiki]
2. Run `kitchen converge migurski-testing-ubuntu-1804`
Result
---
Still seeing some late-stage failures detailed in this log, but gets further than previously: https://gist.github.com/migurski/e08c0207d18462258498b198f1ae3607
> Fixed small bugs after trying wiki test-kitchen

- cookbooks/munin/templates/default/munin.conf.erb
We have nginx per-cache, but no total graph.
I'm not sure how I can test this locally, is there any sensible way?
> Add Nginx totals to tile.openstreetmap.org munin

- cookbooks/tilecache/templates/default/nginx_tile.conf.erb
These are all coming with a referer of `Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)` so we could block that instead
> Add fake MS referer to block list

- cookbooks/tilecache/templates/default/nginx_tile.conf.erb
Where possible these sites have been contacted. Some of the user-agents do not provide enough information to contact them.
> Block more heavy user apps and sites

- cookbooks/tilecache/templates/default/nginx_tile.conf.erb
Google was routing their emails to spam and they asked for more time.
> Hold off on Wialon block

- cookbooks/dmca/files/default/html/index.php
Add fully formatted complainant address to dmca mail body for easy copy/pasting in responses
as discussed in the dwg. 
( $reply_address can potentially be used for a Reply-To header )
> RFC-formatted complainant address for easy copy/paste

- cookbooks/devices/templates/default/udev.rules.erb
`group_thread_cnt` was added in kernel 4.9+ to allow mdraid to use multiple threads for some RAID5 and RAID6 operations.
With fast SSD and NVMe disk mdraid using a single thread is often a performance bottleneck.
> Allow md raid to use multiple threads for RAID5 and 6

- cookbooks/planet/files/default/replication-bin/replicate-changesets
- cookbooks/planet/recipes/replication.rb
- cookbooks/planet/templates/default/changesets.conf.erb
When the changeset replication runs slow, a lot of processes queue up trying to get the lock. I'm not totally sure, but it looks like they then get woken up in a random order, resulting in weird out-of-order behaviour.
This patch simplifies that process in two ways:
1. If the lock isn't acquired, the process exits. This means much less (perhaps zero) lock queueing.
2. Using a separate `lockfile`, rather than the current state file. Since the new state file is moved into place over the old one, it was effectively unlocking at that point for _new_ processes. But would also unblock an old process which still had the old (now unlinked) file descriptor open.
Hopefully between these two changes, it resolves some of the brokenness that plagues changeset replication! :-)
> Attempt to fix changeset replication lock queueing.

- .rubocop.yml
When Ruby 2.3 support was dropped in RuboCop they changed the Layout/HeredocIndentation to only support squiggly so setting this just causes it to warn. Just enable it instead.
See https://github.com/rubocop-hq/rubocop/pull/8056
Signed-off-by: Tim Smith <tsmith@chef.io>
> Avoid warning running cookstyle due to Layout/HeredocIndentation

- cookbooks/planet/recipes/dump.rb
New version has fixes for memory explosion and `pg_restore` argument changes.
* The behaviour of the standard C++ library has been fixed so that `std::vector<>::clear()` _does not_ deallocate memory. It seems that previous versions of the library _did_ deallocate, which is not standards conforming, but meant that a bug in `planet-dump-ng` went unnoticed and its memory usage exploded under the new version of the library.
* The `pg_restore` tool from PostgreSQL now requires either a database name or file output argument. Previously the default was to output to stdout, but now this is a hard requirement.
> Bump planet-dump-ng version

- cookbooks/planet/recipes/dump.rb
This includes a concurrency limit for disk-write threads, which hopefully slows the process down to the point where it's not using infinite memory. I've left it set at the default of 16, but we can use the `--max-concurrency` argument to bring it down if it's still using too much memory.
> Bump planet-dump-ng version to v1.1.8

- cookbooks/planet/recipes/default.rb
The old planet file cleanup cron rule is intended to run on the first Monday of each month. Unfortunately, this is slightly difficult to write because cron triggers on [either the day-of-month or day-of-week](https://linux.die.net/man/5/crontab) fields, not both. The fix suggested in the man page is to use a `test $(date %u) -eq 1 &&` to filter the command execution. However, to make things more complicated, the percent sign is a special character for cron (it's an escaped newline) and regular uses of `%` must be backslash escaped.
Long story short, the `date \%u` in the template file needs an extra `\` if it is to be used in a quoted Ruby string. (Although it would be nice if the `cron_d` resource handled proper escaping to avoid cron's `%`-related footguns, apparently it passes the …
> Fix escaping in old-planet-file-cleanup cron rule.

- cookbooks/civicrm/recipes/default.rb
This fixes the issue where git module is unable to checkout a hash for the civicrm.
> civicrm: checkout full depth on extensions

- cookbooks/wiki/templates/default/mw-ext-MultiMaps.inc.php.erb
I would like to update the list of tile layers of the wiki's MultiMaps extension, so I equals the list of featured tile layers. 
I opened the similar PR #278 in February 2020 including OSM-FR tile layer, but in response to https://github.com/cquest/osmfr-cartocss/issues/65#issuecomment-673613832, I would like to leave that one out for now.
> Align wiki tile layer list with featured tile layers at osm.org

- cookbooks/mediawiki/resources/site.rb
- cookbooks/mediawiki/templates/default/mw-ext-SlippyMap.inc.php.erb
This is the last one of a series of PRs to replace MediaWiki's SlippyMap extension with MultiMaps extension. The plan and subsequent discussion can be found in #241 (see also Firefishy/SlippyMap/issues/2).
> remove SlippyMap extension from all wikis

- cookbooks/devices/templates/default/udev.rules.erb
We don't currently have any Intel Corporation Ethernet Connection I354, but I add to the list as I see NICs.
> devices: Additional NIC ring tuning

- cookbooks/planet/recipes/dump.rb
Update to the latest version of planet-dump-ng, which changes the order of tags in the output file to match that used by other tools. Planet-dump-ng already has a _consistent_ ordering, but not a natural one. The new ordering sorts tag keys as UTF-8 encoded strings of bytes, so it's not a "proper" Unicode string sort but still more understandable than the previous method.
See [osmdbt#29](https://github.com/openstreetmap/osmdbt/issues/29) for previous discussion and more information.
> Bump planet-dump-ng version for tag order change.

- cookbooks/planet/files/default/cgi/HEADER.cgi
makes existence of BitTorrent files more prominent.
> Mention .torrent files too in header (instead of only mirrors)

- cookbooks/dmca/files/default/html/index.php
DMCA form mails lack a content-type header. Quite often non-latin, such as Persian, is filled in, typically in utf-8, which currently looks garbled in the receiving mail client.
This PR adds the same content-type that the html page uses itself, and is the most likely to be filled by the form users.
> DMCA form: add Content-Type header to generated email

- cookbooks/tile/templates/default/render-lowzoom.erb
- cookbooks/tile/templates/default/renderd.conf.erb
- cookbooks/tile/templates/default/update-lowzoom.erb
I had a look at the CPU usage of our render servers. Below is Odin, which is typical
They never reach 100% utilization, which is good, but I think we're leaving too much idle right now.
I graphed the idle CPU with the PromQL `sum by (instance) (rate(node_cpu_seconds_total{instance=~"albi|odin|ysera|rhaegal",mode="idle"}[$__rate_interval]))` and looked at a peak period where those four servers were capped in CPU and found they all had at least 2 threads idle.
pyrene and bowser did not hit a CPU cap.
> Only reserve one CPU for other tasks on render servers

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
I try to explain the change without commenting to lengthy. 
**Current (faulty) behaviour:** When a user with a non-English interface clicks on a link in the sidebar a. k. a. menu of the wiki, they go to the English target page of the link.
**Expected correct behaviour:** The user clicks on the link and arrives at the page in the appropriate language
**What the change technically does:** It changes the MediaWiki interface configuration pages for which the system accepts translations. The [Sidebar configuration page](https://wiki.openstreetmap.org/wiki/MediaWiki:Sidebar) contains the menu entries. Each entry links to a page `____-url` which contains the link target. Link targets can be translated by wiki admins appending a slash and a language code to the page name, so …
> Allow the translation of MediaWiki sidebar

- cookbooks/dev/templates/default/dev.html.erb
Update some links on our little dev server homepage.
* The rails port install instructions are now in github.
* It's no longer serving up SVN branches (These days it's all github. That branches list is maintained here in chef https://github.com/openstreetmap/chef/blob/master/roles/dev.rb#L100 but I think that would be a bit of tangled thing to link to from this homepage)
> Update links on dev server homepage

- cookbooks/planet/templates/default/planetdump.erb
Please add new mirror as web seed source to new torrents being created.
It is a Mail.ru Group based planet mirror, located at Russia, Moscow.
It is already described and advertised at https://wiki.openstreetmap.org/wiki/Planet.osm#Planet.osm_mirrors
> Add new mirror as webseed to new torrents

- cookbooks/mediawiki/resources/site.rb
- cookbooks/mediawiki/templates/default/mw-ext-SimpleMap.inc.php.erb
SimpleMap extension (also known as [Simple Image MediaWiki extension](https://wiki.openstreetmap.org/wiki/Simple_image_MediaWiki_Extension)) requires an external [static map image](https://wiki.openstreetmap.org/wiki/Static_map_images)/tile stitching service to display rendered maps in the wikis. The two most recent providers cancelled their service, so the extension shows an empty image box since at least February 2020. [Multiple solutions](https://github.com/Firefishy/SimpleMap/issues/4#issuecomment-590058644) were suggested. However, nobody was interested in providing a tile stitching service and maintaining the extension. It remained broken for 15 months. 
The last suggestion was to replace this extension with "MultiMaps" extension installed on wiki.osm.org already. Following …
> Remove SimpleMap MediaWiki extension from all wikis

- cookbooks/planet/recipes/current.rb
The planet update fails quite often for unknown reasons on the taginfo server. Maybe this is due to the process creating the hourly file running in the exact same moment or some other problem. This changes moves the cronjob a bit later to see whether it works better.
> Run planet update for taginfo later

- cookbooks/planet/templates/default/planet-update-file.erb
Increase verbosity level of pyosmium-up-to-date in /usr/local/bin/planet-update to help finding out why it fails so often.
> Increase log verbosity level of planet update

- cookbooks/planet/templates/default/planet-update.erb
The planet update log of a run was writing over the previous log instead of appending. The log file is already rotated correctly, so it is not growing without bounds with this change.
> Append to planet update log instead of overwriting

- cookbooks/tile/attributes/default.rb
- roles/pyrene.rb
This is 15 TPS per server, except for pyrene which needs 30.
Now that the rate limiting is working I reviewed IPs exceeding 20
TPS on an hour basis, looking at several days, and they were all
scrapers, or fakes which I would normally block if not for the effort.
I found no non-scraping proxies or NAT.
> Decrease tile rate limit to 30 TPS

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
- cookbooks/mediawiki/templates/default/mw-ext-SpamBlacklist.inc.php.erb
- cookbooks/mediawiki/templates/default/mw-ext-TitleBlacklist.inc.php.erb
The first commit enables logging for two anti-spam wiki extensions. Currently, both [Spam blacklist log](https://wiki.openstreetmap.org/wiki/Special:Log?type=spamblacklist) and [Title blacklist log](https://wiki.openstreetmap.org/wiki/Special:Log?type=titleblacklist) are empty because logging is not enabled. I would like to use the logs to find spammers as well as wrong hits. By default, one log is visible to all signed-in users the other one is visible to administrators only. I explicitly set the viewing permissions to avoid changes with updates. 
The second commit removes the spam regex from the configuration files. I created a [similar abuse filter](https://wiki.openstreetmap.org/wiki/Special:AbuseFilter/11) instead. Abuse filters are editable by wiki administrators. The regex can be …
> Increase usability of anti-spam features

- cookbooks/dhcpd/recipes/default.rb
- cookbooks/dhcpd/templates/default/dhcpd.conf.erb
Add PXE support using ipxe with menus from netboot.xyz
This greatly simplifies my life installing ubuntu, burn-in tests or final machine wipe.
> Add PXE boot support using ipxe netboot.xyz

- roles/equinix-dub.rb
Equinix Dublin has a 10Gb uplink and significantly faster switches.
We had to disable BBR in Equinix Amsterdam due to the uplink going over capacity causing switch/router port buffer overrun and packet loss.
The same scenario is very unlikely to happen in Dublin with machines limited to 2x 1Gb each and uplink allowing 10Gb.
> Enable BBR at Dublin with sufficient uplink and switch capacity

- cookbooks/openssh/attributes/default.rb
- cookbooks/openssh/templates/default/sshd_config.conf.erb
- roles/dev.rb
Disable openssh password authentication by default.
Closes: https://github.com/openstreetmap/operations/issues/603
> openssh: disable password authentication by default (except dev)

- cookbooks/tilelog/recipes/default.rb
- cookbooks/tilelog/templates/default/tilelog.erb
Ref: https://github.com/openstreetmap/tilelog/issues/2
This upgrades to tilelog 1.0.0 which allows producing multiple files, one of which is the existing log, the other is a log of top-usage websites.
The LWG has okayed showing aggregate referer information, and this requires >= 432000 requests/day to make the list.
An example of hosts decompressed is
```
"www.openstreetmap.org",1453.99,464.1
"localhost",310.3,26.29
"",151.82,28.89
"dro.routesmart.com",136.46,39.68
"www.openrailwaymap.org",123.65,18.54
"www.ad-production-stage.com",107.98,0.05
"r.onliner.by",96.64,1.78
"solagro.org",91.42,0.16
"tvil.ru",87.83,1.53
"eae.opekepe.gov.gr",84.88,12.98
"www.mondialrelay.fr",74.0,2.32
"www.lightningmaps.org",63.44,1.93
"nakarte.me",63.22,14.01
"qualp.com.br",55.1,0.74 …
```
> Produce per-host referer logs for tiles

- cookbooks/tilelog/recipes/default.rb
This strips subdomains from the host list, merging into the privatesuffix (e.g. foo.example.com becomes example.com)
> Upgrade to tilelog 1.2.0

- cookbooks/tilelog/recipes/default.rb
1.3.0 adds filtering to not count apps using webview as websites.
> Update to tilelog 1.3.0

- cookbooks/prometheus/recipes/server.rb
Although long-term we want to move to using external storage (https://github.com/openstreetmap/operations/issues/484), this will give us a bit more time to look at metrics before they get flushed out of storage, which will help until we can get promscale working.
> Increase prometheus retention time to 30d

- cookbooks/supybot/templates/default/git.conf.erb
These branches are no longer used, as versions this old aren't maintained.
> supybot: remove old osm2pgsql branches

- cookbooks/tile/recipes/default.rb
Fixes #184
Fixes https://github.com/openstreetmap/operations/issues/582
Calendar expression testing:
```
$ systemd-analyze calendar "Fri *-*-* 23:00:00 UTC"
Normalized form: Fri *-*-* 23:00:00 UTC
Next elapse: Fri 2022-07-15 16:00:00 PDT
(in UTC): Fri 2022-07-15 23:00:00 UTC
From now: 1 day 15h left
```
For the production tileservers, pyrene finishes in 6h; bowser, balerion, odin, and ysera finish in 3:15; and culebre and nidhogg finish in 1:00.
The older unused servers take longer, but those aren't a consideration.
At 2300 UTC on Friday all the servers are at a low load point. I considered scheduling towards the end of the weekend, but had a slight preference for the start.
I also considered local time zones when the servers have slightly lower load, but the load difference is not huge, …
> Run low-zoom re-render weekly

- cookbooks/hardware/recipes/default.rb
- cookbooks/hardware/templates/default/ilo-defaults.xml.erb
- Automatically power on servers after random interval
- HP Dynamic Power Savings mode (HP Default)
- Set server name in ilo
- Unset max power (Watt) cap.
Link: https://github.com/openstreetmap/operations/issues/686
> hardware: Set OSM ilo defaults

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
The pull request removes the automatic account confirmation mechanism for "private account" wikis and "private site" wikis. It first sets the required number of edits and the required account age to 0 and then merges and deletes the "autoconfirmed" user group (identical as how the "interface admin" user group is deleted). The rest of the change moves code in the configuration file and adds comments. This is done to improve readability and to load extensions before manipulating those user rights. [In a separate file](https://github.com/openstreetmap/chef/blob/6c869d1b5625e8cbe1c091ed869c162bc9a6db59/cookbooks/mediawiki/templates/default/mw-ext-ConfirmEdit.inc.php.erb), the ConfirmEdit extension includes the configuration ```$wgGroupPermissions['autoconfirmed']['skipcaptcha'] = true;``` …
> remove account confirmation for private wikis

- cookbooks/tile/recipes/default.rb
- cookbooks/tile/templates/default/apache.erb
A first attempt at implementing https://github.com/openstreetmap/operations/issues/679.
Things it still needs:
* Allowing statuscake check ranges (do we have a source for these?)
* Allowing OSMF IP ranges (this would be a massive pain though we could do the main data centres easily)
> Block requests for tiles unless they come from a CDN node

- cookbooks/tilelog/templates/default/tilelog.erb
The files produce list apps, which are, approximately, non-browser users. The actual value is produced from user-agent, referer, and x-requested-with to produce something that meaningfully identifies the app.
App versions are dropped in order to get a more accurate total picture of usage coming from an app.
The data produced requires 432k requests before something appears in the output file, so it will not be a user-identifying user-agent, but something from a common browser or app.
> Produce app info files with tilelog

- cookbooks/tilelog/templates/default/tilelog.erb
All the tile logging operates on UTC, so explicitly state so
> Use UTC date when generating tile logs

- cookbooks/tile/recipes/default.rb
- roles/tile.rb
Untested - not sure how to best test this. The style download should run before the CartoCSS is compiled.
I figure updating the fonts every new release is frequent enough, as they don't change *that* often.
Fixes #522
> Update to osm-carto v5.6.0

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
As per https://www.mediawiki.org/wiki/Manual:Using_custom_namespaces
the string values in $wgExtraNamespaces have to use underscores
instead of spaces ... otherwise MediaWiki wrongly recognizes
"Proposal_talk:Foo" to be in the main namespace.
> Fix $wgExtraNamespaces[NS_PROPOSAL_TALK]

- cookbooks/dev/templates/default/apache.phppgadmin.erb
- cookbooks/dev/templates/default/apache.user.erb
- cookbooks/dmca/templates/default/apache.erb
- cookbooks/donate/templates/default/apache.erb
- cookbooks/forum/templates/default/apache.erb
- cookbooks/matomo/templates/default/apache.erb
- cookbooks/mediawiki/templates/default/apache.erb
- cookbooks/nominatim/templates/default/nginx.erb
- cookbooks/php/resources/fpm.rb
- cookbooks/php/templates/default/pool.conf.erb
- cookbooks/wordpress/templates/default/apache.erb
`apparmor-profiles` package on errol (and elsewhere) provides a default php-fpm profile.
The socket is expected with name: `@{run}/php{,-fpm}/php*-fpm.sock`
> Name php-fpm socket to work with apparmor-profiles

- cookbooks/chef/recipes/default.rb
- cookbooks/dev/recipes/default.rb
- cookbooks/gps-tile/recipes/default.rb
- cookbooks/hardware/recipes/default.rb
- cookbooks/planet/recipes/replication.rb
- cookbooks/rsyncd/recipes/default.rb
- cookbooks/tile/recipes/default.rb
- cookbooks/tilelog/recipes/default.rb
- cookbooks/web/recipes/rails.rb
Renice background service to allow full speed important services.
Reniced services will be ignored for ondemand CPU scaling saving power.
Signed-off-by: Grant Slater <git@firefishy.com>
> Renice background services

- cookbooks/apt/recipes/default.rb
- cookbooks/apt/templates/default/sources.list.erb
This is used for example when running test kitchen on recent Apple devices.
> Add initial support for other ubuntu ports (eg: arm64)

- cookbooks/dev/recipes/default.rb
Could we please install the `pandoc` package on the dev server? Needed for [FHODOT statistics](https://gregrs.dev.openstreetmap.org/fhodot/summary.html). Thanks.
> Add pandoc package to dev server

- cookbooks/tilelog/recipes/default.rb
1.4.1 detects more UAs for combining versions.
> Upgrade to tilelog 1.4.1

- cookbooks/tile/recipes/default.rb
OpenStreetMap Carto requires, and we use, at least 3.0.22.
> Specify mapnik version for CartoCSS

- roles/tile.rb
Fixes a typo causing issues with fonts.
> Update to OpenStreetMap Carto v5.6.2

- cookbooks/letsencrypt/files/default/bin/renew
- cookbooks/letsencrypt/templates/default/request.erb
Use the letsencrypt default certificate chain as recommended by API.
Previously chain of trust needed to be overridden for extended compatibility, I believe this is no longer required.
[Letsencrypt have a complicated chain of trust](https://letsencrypt.org/certificates/), it likely best to use their default recommended chain.
> letencrypt: Use default certificate chain

- cookbooks/wiki/templates/default/mw-ext-Kartographer.inc.php.erb
Following openstreetmap/chef#552, there are still issues with string insertions into the tile URLs. On a Windows computer some zoom factor is inserted into the URL so the extension tries to access `https://tile.openstreetmap.org/12/2053/1365@1.3x.png?lang=en` instead of `https://tile.openstreetmap.org/12/2053/1365.png?lang=en`. AFAIK switching-off high-DPI should fix that.
The second addition configures the extension to stop requesting images for map pins from the tile servers. This behavior was mentioned at the [original proposal](https://github.com/openstreetmap/operations/issues/749) already. I found an previously undocumented setting that will use a static image included in the extension.
> Attempt to fix missing images in Kartographer wiki extension

- cookbooks/community/templates/default/web_only.yml.erb
- cookbooks/docker/recipes/default.rb
- cookbooks/docker/templates/default/daemon.json.erb
Uses the experimental `ip6tables` feature which isn't ideal, but seems to work ok.
Fixes: [#843](https://github.com/openstreetmap/operations/issues/843)
> docker: Enable IPv6 support using ULA

- .kitchen.yml
- cookbooks/awscli/README.md
- cookbooks/awscli/attributes/default.rb
- cookbooks/awscli/metadata.rb
- cookbooks/awscli/recipes/default.rb
- test/integration/awscli/serverspec/awscli_spec.rb
Add `awscli` cookbook.
The distro versions of aws cli not supported by AWS. Some features only work reliably with newer releases eg: `aws s3 sync`
The cookbook will be used later.
> Add awscli cookbook

- .kitchen.yml
Seems to improve the total runtime a bit...
~ [6h 30m](https://github.com/openstreetmap/chef/actions/runs/5777866892/usage) -> [6h 8m](https://github.com/openstreetmap/chef/actions/runs/5792869209/usage)
> Enabled eatmydata in kitchen

- cookbooks/tilelog/recipes/default.rb
- cookbooks/tilelog/templates/default/tilelog.erb
These new tables allow for generalization of data and reducing the data stored. They're not yet queried, that will come in a later version, but this allows population of the tables to start.
> Update to tilelog 1.6.0 and generate new tables

- cookbooks/tilelog/recipes/default.rb
The queries on 1.6.0 were running into resource limits when aggregating on busy days. This changes them to split up the work by hour.
> Update to tilelog 1.6.1

- cookbooks/db/templates/default/wal-g.erb
WAL-G uploads LZ4 by default, but seem to cycle through the supported compressors when downloading.
Extract from Cloudwatch logs
```
"arn:aws:s3:::openstreetmap-wal/wal_005/000000010001016A00000058.lzma" (GET 404)
"arn:aws:s3:::openstreetmap-wal/wal_005/000000010001016A00000058.lz4" (PUT)
"arn:aws:s3:::openstreetmap-wal/wal_005/000000010001016A00000058.gz" (GET 404)
"arn:aws:s3:::openstreetmap-wal/wal_005/000000010001016A00000058.br" (GET 404)
"arn:aws:s3:::openstreetmap-wal/wal_005/000000010001016A00000058.lzo" (GET 404)
"arn:aws:s3:::openstreetmap-wal/wal_005/000000010001016A00000058.zst" (GET 404)
"arn:aws:s3:::openstreetmap-wal/wal_005/000000010001016A00000058.lz4" (GET 200)
```
Try explicitly set `WALG_COMPRESSION_METHOD` in an attempt to stop this behaviour.
Also renamed …
> postgres: explicitly specifiy WAL-G compressor

- cookbooks/apt/recipes/yarn.rb
`apt update` was complaining about an expired key. I checked the setup instructions and found the key has changed, and got the new one with `curl -s https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --show-keys --with-colons - | awk -F':' '$1=="pub"{print $5}'`
I validated this from two machines for paranoia.
> Update yarnpkg APT signing key

- .github/workflows/test-kitchen.yml
- .kitchen.yml
Switch to GHCR.io dokken images for improved image download latency and to avoid potential docker hub access limits.
> Use GHCR dokken images in test kitchen

- cookbooks/foundation/recipes/wiki.rb
- cookbooks/mediawiki/templates/default/apache.erb
This change changes https://wiki.osmfoundation.org/ site to https://osmfoundation.org/
Allows / to serve /wiki/Main_Page without a redirect.
> Add allow wiki main page on root + osmf site url change

- cookbooks/planet/templates/default/planet-notes-dump.erb
Change the daily notes dump to copy the results to the S3 bucket.
This assumes that the planet user has valid AWS credentials which is waiting on a PR from @Firefishy.
> Copy notes dumps to S3

- cookbooks/db/recipes/master.rb
Fixes cookstyle complaint:
...............................................................C.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Offenses:
cookbooks/db/recipes/master.rb:87:22: C: [Correctable] Style/MutableConstant: Freeze mutable objects assigned to constants. CGIMAP_PERMISSIONS = { ...
^ …
> Freeze mutable objects assigned to constants

- cookbooks/podman/resources/service.rb
PR to avoid starting the service and then restarting it on first run.
Separate out the start and use service status to make it a "noop" if service is already running due to restart.
> podman: avoid starting and immediate restart on first run

- cookbooks/podman/resources/service.rb
Workaround podman's crun bug in Ubuntu 22.04: https://github.com/containers/podman/issues/9752
The bug seems to happen 1 in 10 in some environments (like: GitHub Actions), so 4 retries drops the odds down to hopefully ~ 0.01%.
> podman: workaround ubuntu 22.04 crun bug

- .github/workflows/test-kitchen.yml
- .kitchen.yml
- cookbooks/chef/recipes/default.rb
- test/integration/chef/inspec/chef_spec.rb
Add basic chef test to chef service + timer installed and the binary functions.
Added workaround for missing Debian ARM builds by using ARM build from Ubuntu.
> Add test for chef cookbook

- cookbooks/planet/files/default/cgi/HEADER.cgi
- cookbooks/planet/files/default/html/style.css
This is a rebase of the web styling changes for planet.openstreetmap.org in #574, which I forgot about. This change switches the layout from tables to FlexBox which makes the content more readable on smaller screens, and also more accessible. It doesn't contain any substantive wording changes.
I made these changes in a local copy of the HTML so I haven't fully tested the generation, but the diff looks fairly straightforward.
> Improve planet.osm web styling

- cookbooks/apache/attributes/default.rb
iD tiles map requests.
It appears 4x3 tiles are common, 12 requests + 12 CORS requests. (24 req)
If the user also scrolls the map this can exceed current 50 req/s.
> apache: increase mod_evasive page_count to reduce iD false positives

- cookbooks/otrs/attributes/default.rb
- cookbooks/otrs/recipes/default.rb
- cookbooks/otrs/templates/default/sudoers.erb
znuny only supports upgrading one minor version at a time. Future upgrades will be 6.0.x -> 6.1.x -> 6.2.x etc
> otrs: upgrade to latest znuny 6.0.x release

- cookbooks/networking/recipes/default.rb
- cookbooks/networking/templates/default/dokken.network.erb
This lets `systemd-networkd` think it is managing the networking in podman / docker and ensures that `systemd-networkd-wait-online` does not wait for timeout on systemd services which rely on networking.
> systemd-networkd-wait-online waiting for timeout in dokken

- .kitchen.yml
- cookbooks/otrs/recipes/debian.rb
- cookbooks/otrs/templates/default/apache-debian.erb
- cookbooks/otrs/templates/default/dbconfig.config.erb
- test/data_bags/otrs-debian/passwords.json
- test/integration/otrs-debian/inspec/apache_spec.rb
Add chef cookbook `otrs::debian` for installing OTRS/Znuny from debian's otrs2/znuny package.
> otrs: Add otrs::debian for installing otrs via deb package

- cookbooks/web/recipes/rails.rb
`openstreetmap.COM` is a commonly used incorrect domain for us.
The domain displays an HTTPS certificate error. Some users may still have a redirect cached and will not see the error (Redirect cached until 2038)
This PR adds the certificate so that the `openstreetmap.COM` will be correctly redirected without a potential certificate issue.
> web: add openstreetmap.com to certificate

- cookbooks/ohai/resources/plugin.rb
`/etc/chef/ohai/plugins/` is the standard ohai plugin path, previously we used `/etc/chef/ohai/` and appended in that path via chef client.rb `ohai.plugin_path << "/etc/chef/ohai"`
This code changes to use the standard path and has cleanup code to remove plugins from the old path.
> ohai: use standard plugin path

- cookbooks/apache/templates/default/evasive.conf.erb
Currently mod-evasive uses `403 - Forbidden`, instead use `429 - Too Many Requests` instead to clearly identify the responses when mod-evasive is triggered.
> apache: use 429 error for mod-evasive

- cookbooks/prometheus/templates/default/alert_rules.yml.erb
My first attempt at prometheus alert rule writing. Not sure I got it right.
What I'm trying to do is to trigger an alert when the number of connections in writing in [Nominatim's 'Active Connections by State' graph](https://prometheus.openstreetmap.org/d/6qvCSGtnz/nominatim) goes over 2.5k. This intentionally works on the sum of all Nominatim servers because it'd need different limits for the different servers otherwise.
> Add prometheus alert for too many parallel connections to nominatim

- cookbooks/apache/templates/default/httpd.conf.erb
Only show show `Server: Apache/2.4` instead of full `Server: Apache/2.4.54 (Ubuntu)` response header.
The full version is unnecessary level detail and may cause false positive security reports.
> apache: only show major/minor apache version in response header

- .github/workflows/test-kitchen.yml
Workaround anonymous limits of Docker Hub registry by having the GHA login.
> Add docker hub login to avoid hub IP limits

- cookbooks/tile/recipes/default.rb
This avoids failures on Debian systems.
> Install system pyotp

- cookbooks/apt/recipes/default.rb
Enable backports version of `systemd` packages.
> apt: enable systemd backport in Debian

- cookbooks/vectortile/recipes/default.rb
This domain is pointed at fastly, not the backend
> Don't try to get a cert for vector.osm

- cookbooks/tools/recipes/default.rb
I figure curl is generally useful, and it's not part of a minimal debian install
> Install curl as part of tools

- roles/vectortile.rb
This value scales with number of cores instead of a flat 250
> Rely on max_connections set in attributes

- cookbooks/tile/recipes/default.rb
The logic that generates the renderd age metric can be removed when there is enough data for the new metric in Prometheus.
This logic exists in the prometheus exporters package.
> tile: use osm2pgsql-replication promethus

- .kitchen.yml
I created https://github.com/Firefishy/chef-docker-image which uses github actions to clone the official Chef docker image and push it to GHCR.
This is to avoid the extremely low docker hub download limits which are breaking our tests.
> Use chef image clone to ghcr to workaround docker hub limits

- cookbooks/vectortile/recipes/default.rb
- cookbooks/vectortile/templates/default/import-planet.erb
- cookbooks/vectortile/templates/default/tiles-rerender.erb
- cookbooks/vectortile/templates/default/vector-update-notile.erb
- cookbooks/vectortile/templates/default/vector-update-tile.erb
This uses the new flex expiry code in spirit/shortbread to reduce the number of tiles that need to be re-rendered each update.
> vectortile: Use flex expiry

- cookbooks/taginfo/recipes/default.rb
New source "sw" is now available in the software and needs to be enabled.
(It looks at iD and JOSM config)
> Add new source for taginfo

- cookbooks/planet/files/default/replication-bin/replicate-changesets
I wanted to check how replicate-changesets works with https://github.com/openstreetmap/openstreetmap-website/pull/5309 and it didn't run for a number of reasons. First, `YAML.safe_load` arguments are outdated since https://github.com/ruby/psych/commit/0767227051dbddf1f949eef512c174deabf22891 and an update like https://github.com/openstreetmap/chef/commit/8061c292a2490f50f1e84a5bccde1b45e5d3d511 is needed.
> Update YAML.safe_load arguments in replicate-changesets

- cookbooks/planet/files/default/replication-bin/replicate-changesets
If I use readme at https://github.com/zerebubuth/openstreetmap-changeset-replication as a guide, it says "a state file, which can be empty the first time it's used". But that's not going to work because an empty file is read as `nil`, then the code tries to access elements of that `nil` and crashes.
Here I change an empty state_file to be read as an empty hash.
> Use empty hash fallback when loading state file in replicate-changesets

- cookbooks/planet/files/default/replication-bin/replicate-changesets
Looking at the readme in https://github.com/zerebubuth/openstreetmap-changeset-replication you can see this line in the example config:
```
data_dir: replication/
```
Looks like you can specify a relative path as `data_dir`. But actually you can't, because the loop I modify in this PR will never terminate. The server config avoids this issue by using an absolute path:
https://github.com/openstreetmap/chef/blob/e4330da209a809e67d03ff9e2b0a7f4bcac55863/cookbooks/planet/templates/default/changesets.conf.erb#L3
> Terminate fdirsync loop when "." is reached in replicate-changesets

- cookbooks/planet/files/default/replication-bin/replicate-changesets
- `select now()` gives you time with timezone
- `select created_at` etc give you time without timezone because we don't store timezones
- `Time.parse()` on time without timezone parses it as a local time
- comparisons between times with/without timezones are broken both in ruby and in db queries
To fix all this I'm adding `at time zone 'utc'` to every time value from db that doesn't have a timezone.
> Select db dates at utc in replicate-changesets

- README.md
- to automate the configuration...
- e.g.,  
see:
https://www.merriam-webster.com/dictionary/e.g.#examples
> fix: README.md grammar punctuation

- cookbooks/imagery/templates/default/nginx_imagery_layer_fragment.conf.erb
We have WebP layers in the editor-layer-index now https://github.com/osmlab/editor-layer-index/issues/1890 and it would be nice to access the OSM hosted imagery layers via WebP for lower bandwidth with transparency support.
I'm unsure about any CPU load implications.
> enable webp support for imagery layers

- cookbooks/imagery/recipes/au_act_aerial.rb
- roles/imagery.rb
We have [permission to use](https://wiki.openstreetmap.org/wiki/File:ACT_Government_20180314_Permission_to_Incorporate_CCBY_data_into_OSM.PDF) ACT CC BY imagery in OSM and have a [few layers in the ELI](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/oceania/au/act), however recently these have only been published as WMTS with EPSG:7855.
This works in JOSM, but unfortunately WMTS won't (unlike WMS) accept a request to serve images in Web Mercator and iD doesn't support reprojecting image tiles from EPSG:7855 to WebMercator.
However since you're running a MapServer service already, perhaps we can include the configuration needed to proxy these layers from EPSG:7855 tiles to Web Mercator tiles?
I've tested a version of this mapserver .map file locally and it seems to be …
> add au_act_aerial mapserver imagery

- cookbooks/dev/templates/default/apache.rails.erb
- cookbooks/web/templates/default/apache.frontend.erb
In https://github.com/openstreetmap/openstreetmap-website/pull/5591 I added a standard `create` action for elements to OSM API. It's performed by POSTs at element index routes:
- `/api/0.6/nodes`
- `/api/0.6/ways`
- `/api/0.6/relations`
However those are still mapped to cgimap on the servers, even though cgimap doesn't support POST requests at these paths. cgimap doesn't have any functionality for single-element writes and there are no plans to add it, only changeset uploads are supported for writing map data.
> Pass only HEAD and GET /api/0.6/(elements) requests to cgimap

- cookbooks/tile/recipes/default.rb
- cookbooks/tile/templates/default/export.erb
This PR adds OSM attribution to the map export, both for vector and raster formats. Besides, this PR adds webp image format.
I introduced a new dependency on python3-pil package to enable the png->{webp,jpeg} conversion.
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/551
> Add copyright/attribution message to downloaded map images

- cookbooks/web/templates/default/apache.frontend.erb
`GoogleAssociationService` sends around 1,000,000 requests per day to `/.well-known/assetlinks.json`, we respond fairly quickly with 404 via rails.
This PR hotwires the requests to instead have apache response directly with an HTTP "429 - Too Many Requests" error.
> web: Ignore GoogleAssociationService assetlinks.json requests

- cookbooks/vectortile/attributes/default.rb
- cookbooks/vectortile/recipes/default.rb
This allows upgrading servers one-by-one in cases where a reload is needed.
> vectortile: Make the spirit and themepark versions attributes

- .kitchen.yml
Due to differences in how podman and docker treat volumes, we have to hack in a workaround for podman to start the chef container up before it runs a suite.  Otherwise you get a failure to find the chef-client binary
https://github.com/test-kitchen/kitchen-dokken/issues/255 has more information on the cause
> Allow podman to run kitchen tests

- cookbooks/exim/templates/default/exim4.conf.erb
Increase the exim max SMTP message line length so as not to reject some badly formatted emails.
Currently a few `cron.daily` emails are rejected outbound due to line length. (eg: fafnir)
The issue seems common enough that the workaround has been templated:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828801
https://serverfault.com/questions/842176/exim-limiting-number-of-emails-and-cc/881197#881197
> exim: Increase message_linelength_limit to avoid dropping emails

- cookbooks/python/resources/package.rb
> python-package: take into account extra pip source when listing outdated pkgs

- cookbooks/apache/recipes/default.rb
- cookbooks/apache/resources/conf.rb
- cookbooks/apache/templates/default/ssl.erb
Apache cannot cleanly restart if changing ports or shared memory, restart if needed.
Use new restart support if SSL config options are changed.
> Restart Apache in a few extra cases. Remove old ssl stapling config

- cookbooks/web/recipes/frontend.rb
- cookbooks/web/templates/default/apache.frontend.erb
- cookbooks/web/templates/default/security.txt.erb
Add a basic security.txt pointing to the current contact / policy document.
The `Expires` field is required, normalise to only "update" once per day.
> web: Add security.txt
