openstreetmap/chef

- cookbooks/cgiirc/templates/default/cgiirc.config.erb
Would be good to add #osm-ua channel to the http://irc.openstreetmap.org/ page.
> Added #osm-ua channel

- cookbooks/accounts/README.md
- cookbooks/apache/README.md
- cookbooks/apt/README.md
- cookbooks/backup/README.md
- cookbooks/bind/README.md
- cookbooks/blog/README.md
- cookbooks/cgiirc/README.md
- cookbooks/chef/README.md
- cookbooks/civicrm/README.md
I've started writing brief explanations of each cookbook in the README, but it'll take a while for me to finish since there's a fair few of them and there are many that I'm not familiar with. If there's any reason to think this PR won't be eventually accepted, please let me know before I go too far!
Otherwise, feel free to either wait for the rest to appear, or to merge the changes so far.
> (WIP) Start replacing default readmes with brief explanations

- cookbooks/planet/files/default/replication-bin/replicate-changesets
Trying to track down why sometimes zero-size or invalid files are produced. (See zerebubuth/openstreetmap-changeset-replication#2 for background)
> Added sanity checks to changeset replication

- cookbooks/clamav/README.md
- cookbooks/db/README.md
- cookbooks/dev/README.md
- cookbooks/devices/README.md
- cookbooks/dhcpd/README.md
- cookbooks/dns/README.md
- cookbooks/elasticsearch/README.md
- cookbooks/exim/README.md
- cookbooks/fail2ban/README.md
- cookbooks/forum/README.md
- cookbooks/foundation/README.md
- cookbooks/geodns/README.md
Another 12 READMEs, only another 55 to go :-)
> Add more cookbook READMEs.

- cookbooks/munin/README.md
- cookbooks/mysql/README.md
- cookbooks/networking/README.md
- cookbooks/nfs/README.md
- cookbooks/nginx/README.md
- cookbooks/nodejs/README.md
- cookbooks/nominatim/README.md
- cookbooks/ntp/README.md
- cookbooks/ohai/README.md
- cookbooks/openssh/README.md
- cookbooks/openvpn/README.md
- cookbooks/osmosis/README.md
- cookbooks/osqa/README.md
- cookbooks/otrs/README.md
- cookbooks/owl/README.md
- cookbooks/passenger/README.md
- cookbooks/piwik/README.md
- cookbooks/planet/README.md
- cookbooks/postgresql/README.md
- cookbooks/roundup/README.md
Add another 20 readmes, only another 25 to go!
> Add more READMEs

- cookbooks/tile/templates/default/replicate.erb
* Fixes mixed tabs and spaces
* Rewords a comment I found unclear
> Cosmetic replication script changes

- cookbooks/rsyncd/README.md
- cookbooks/serverinfo/README.md
- cookbooks/snmpd/README.md
- cookbooks/spamassassin/README.md
- cookbooks/squid/README.md
- cookbooks/ssl/README.md
- cookbooks/stateofthemap/README.md
- cookbooks/stats/README.md
- cookbooks/subversion/README.md
- cookbooks/supybot/README.md
> Add more cookbook READMEs

- cookbooks/switch2osm/README.md
- cookbooks/sysctl/README.md
- cookbooks/sysfs/README.md
- cookbooks/taginfo/README.md
- cookbooks/thinkup/README.md
- cookbooks/tile/README.md
- cookbooks/tilecache/README.md
- cookbooks/tilelog/README.md
- cookbooks/tools/README.md
- cookbooks/trac/README.md
- cookbooks/web/README.md
- cookbooks/wiki/README.md
- cookbooks/wordpress/README.md
- cookbooks/xinetd/README.md
- cookbooks/yournavigation/README.md
This is the final batch of cookbook readmes.
> More cookbook readmes

- cookbooks/postgresql/README.md
- cookbooks/postgresql/libraries/postgresql.rb
- cookbooks/postgresql/providers/tablespace.rb
- cookbooks/postgresql/resources/tablespace.rb
Used in the soon-to-be-finished rework of the nominatim cookbook.
> add function to create and delete tablespaces

- cookbooks/supybot/templates/default/git.conf.erb
Per https://github.com/mmueller/supybot-git#configuration multiple branches need to be defined with multiple repository sections
> Track backport branches of osm2pgsql git on irc

- cookbooks/planet/files/default/ccbysa_history_cgi/HEADER.cgi
- cookbooks/planet/recipes/default.rb
Thanks to @pnorman for pointing out the difference between them. Since it confused me, seems worth adding a little comment at the top to say what each one is (and why the earlier one says "final").
> Add explanatory header for full-experimental CC BY-SA planets.

- cookbooks/supybot/templates/default/git.conf.erb
No idea if this works. Ping me on #osm-dev so we can test
> Add vespucci repo

- cookbooks/planet/recipes/replication.rb
- cookbooks/planet/templates/default/replication.cron.erb
- cookbooks/planet/templates/default/users-deleted.erb
No idea if this works and there don't seem to be tests for anything similar. Lets see what CI says.
> Add a script to generate a list of deleted users uids

- cookbooks/wiki/templates/default/mw-ext-Scribunto.inc.php.erb
Should solve
https://lists.openstreetmap.org/pipermail/talk-us/2018-September/018907.html
> increase lua cpu running limit

- cookbooks/wiki/templates/default/mw-ext-Wikibase.inc.php.erb
getting ready for removing search autosuggester
regular search should still include wb item pages
> Include WB items in regular search results by dflt

- cookbooks/wiki/templates/default/mw-ext-Wikibase.inc.php.erb
See https://phabricator.wikimedia.org/T205560
Reopening https://github.com/openstreetmap/chef/pull/195
seems to be working as expected
> Disable Wikibase custom searchbox

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
> removing non-functional web page from allowed external images

- cookbooks/mediawiki/resources/site.rb
- cookbooks/mediawiki/templates/default/mw-ext-MobileFrontend.inc.php.erb
c.f. https://www.mediawiki.org/wiki/Extension:MobileFrontend#Setup_a_skin
fixes #226
> Add new mobile skin: MinervaNeue

- cookbooks/supybot/templates/default/git.conf.erb
The project has changed to owg-website with a different git location
> Update owg-log website

- cookbooks/wiki/recipes/default.rb
> add CodeMirror extension to wiki.osm.org

- cookbooks/supybot/templates/default/git.conf.erb
This is a new long-running branch for schema development
in osm-carto.
> Track osm-carto schema_change branch with osmbot

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
followup for https://github.com/openstreetmap/chef/pull/249 -- made a mistake in the previous commit - the settings should apply to all sites instead.
> apply changes to all sites, not just the private

- cookbooks/dmca/files/default/html/index.php
as discussed in recent DWG meeting, the target wiki page has already been updated accordingly. Intention is to reduce the misdirected requests.
> Improve wording when not to use the DMCA form

- cookbooks/planet/templates/default/planet-mirror-redirect-update.erb
Fixes https://github.com/openstreetmap/operations/issues/355
> Planet redirect: add pbf+full history

- cookbooks/planet/files/default/ccbysa_history_cgi/HEADER.cgi
- cookbooks/planet/files/default/cgi/HEADER.cgi
- cookbooks/planet/files/default/history_cgi/HEADER.cgi
- cookbooks/planet/files/default/html/robots.txt
- cookbooks/planet/files/default/replication-cgi/HEADER.cgi
eg: https://free.nchc.org.tw/osm.planet/
> planet: Resolve header links so it works on mirrors

- cookbooks/supybot/templates/default/git.conf.erb
As the parser is being used more widely, it makes sense to include it here.
> Add https://github.com/simonpoole/OpeningHoursParser

- cookbooks/tilecache/templates/default/nginx_tile.conf.erb
Also fix unnecessary escaping of a #
> Add /n software IPWorks to default libraries

- roles/otrs.rb
> Add email for MWG osmf-talk owner queue

- cookbooks/tilecache/templates/default/nginx_tile.conf.erb
Add additional quick fail 404 tiles.
> tilecache: Add to fast 404 list common off-by-one tiles

- roles/rhaegal.rb
New mb has different network interfaces names.
Will come online probably tomorrow.
> Change rhaegal network interface name

- cookbooks/dns/recipes/default.rb
Update to latest version of dnscontrol.
remote_file uses conditional update by default.
> dns: Update dnscontrol v3.0.0 -> v3.2.0

- cookbooks/planet/templates/default/planetdump.erb
Add Croatian mirror as a webseed for .pbf
> Add croatian mirror to torrent webseed

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
closes https://github.com/openstreetmap/operations/issues/488
> establish confirmed user's group in public wikis

- cookbooks/wiki/templates/default/mw-ext-MultiMaps.inc.php.erb
Synchronise tile layers on the home page with tile layers in the wiki
> Add CyclOSM tile layer to wiki maps

- cookbooks/imagery/recipes/gb_os_sv.rb
Add OS OpenMap Local Oct 2021.
Do not yet merge, kessie is still building the gdaladdo. ETA 8 Dec 2021.
> imagery: Add OS OpenMap Local Oct 2021

- cookbooks/mediawiki/resources/site.rb
- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
Fixes: https://github.com/openstreetmap/operations/issues/466
> mediawiki: add QuickInstantCommons extension

- cookbooks/mediawiki/resources/site.rb
- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
Reverts openstreetmap/chef#490
> Revert "mediawiki: add QuickInstantCommons extension"

- cookbooks/community/recipes/default.rb
First stab and making the web_only container async build instead of rebuild method which causes an ~10min outage.
> community: Use asynchronous bootstap for web_only container

- .github/workflows/cookstyle.yml
- .github/workflows/test-kitchen.yml
Cancel any runs if an a new run is triggered.
PRs and branch builds.
> GH action cancel replaced in-progress runs

- roles/tile.rb
> Update to OpenStreetMap Carto v5.5.0

- cookbooks/networking/recipes/default.rb
Add my roaming wireguard peer.
> networking: Add grant roaming wg

- cookbooks/foundation/recipes/board.rb
- cookbooks/foundation/recipes/dwg.rb
- cookbooks/foundation/recipes/mwg.rb
- cookbooks/foundation/recipes/wiki.rb
- cookbooks/mediawiki/resources/site.rb
- cookbooks/mediawiki/templates/default/mw-ext-ConfirmEdit.inc.php.erb
- cookbooks/wiki/recipes/default.rb
- test/data_bags/wiki/passwords.json
Fixes: https://github.com/openstreetmap/operations/issues/454
> wiki: switch to using hcaptcha

- cookbooks/oxidized/README.md
- cookbooks/oxidized/attributes/default.rb
- cookbooks/oxidized/metadata.rb
- cookbooks/oxidized/recipes/default.rb
- cookbooks/oxidized/templates/default/config.erb
- cookbooks/oxidized/templates/default/logrotate.erb
- cookbooks/oxidized/templates/default/routers.db.erb
- roles/idris.rb
Add oxidized for backing up network device config. Commit config to private git repo.
> Add oxidized backup daemon

- cookbooks/civicrm/attributes/default.rb
Upgrade to version 5.57 of CiviCRM and update some dependencie
> major civicrm upgrade

- cookbooks/mediawiki/templates/default/LocalSettings.php.erb
closes openstreetmap/operations#351
> Activation of "Catwatch"

- cookbooks/tile/files/default/tilejson.json
Replacing #583 since I was cleaning up some issues with my github repos.
De-minified.
> tile: Serve a tilejson pointing at the correct tile URLs

- cookbooks/tilelog/recipes/default.rb
- cookbooks/tilelog/templates/default/tilelog.erb
This creates a new file with information on # of users and traffic by country
> Update to tilelog v1.5.0

- .kitchen.yml
Attempt to fix the broken nested docker test for community
> Specify DNS server to use for dokken

- cookbooks/wordpress/resources/plugin.rb
- cookbooks/wordpress/resources/site.rb
- test/integration/blog/serverspec/wordpress_spec.rb
* Add ability to activate plugins via cli
* Add 2fa and last-login plugins
> wordpress: add 2fa and last-login plugins

- cookbooks/wordpress/resources/plugin.rb
- cookbooks/wordpress/resources/site.rb
* Wordpress site URL under chef control
* Minor quoting fix
> Wordpress additions

- cookbooks/planet/recipes/replication.rb
Earlier in the file replication-hourly is called hourly
> planet: Fix description of replication-hourly unit

- cookbooks/prometheus/recipes/server.rb
Adding arm64 to allow me to more reliably test this cookbook locally.
The Github Actions tests occasionally fail for this cookbook hence my interest in trying to debug locally.
> prometheus: Add arm64 support for server

- cookbooks/planet/recipes/default.rb
- cookbooks/planet/templates/default/apache-latest-planet-filename.erb
- cookbooks/planet/templates/default/apache-s3-ip2region.erb
- cookbooks/planet/templates/default/apache.erb
* Re-implement `apache-latest-planet-filename.erb` script into easier to read python (subjective)
* Add `apache-s3-ip2region.erb` for mapping IP address to preferred bucket (via GeoIP2 Country Continent)
* Add apache redirects to S3, current year only to eu-central-1
> Planet s3 redirect

- cookbooks/planet/templates/default/apache.erb
- cookbooks/planet/templates/default/planetdump.erb
* copy to s3 before available on planet.osm.org
* add S3 to webseeds
> Planet s3 improvements

- cookbooks/systemd/resources/service.rb
- cookbooks/systemd/templates/default/service.erb
Add systemd `RuntimeDirectoryPreserve` support.
> systemd: add RuntimeDirectoryPreserve support

- cookbooks/civicrm/attributes/default.rb
Updates and fixes suggested by the CiviCRM consultant to simplify further investigation
> Updates and fixes for CiviCRM

- roles/cmok.rb
This is for the new vector tile server that will be running at CloudFerro
> Add cmok server

- cookbooks/python/resources/package.rb
Adds the following parameter to 'pip install':
```
--extra-index-url <url>     Extra URLs of package indexes to use in addition to --index-url.
```
I need that for future installations of Nominatim.
> Allow a different source URL for python packages

- cookbooks/web/recipes/rails.rb
Fixes https://github.com/openstreetmap/operations/issues/1101
> Add 2gis to imagery blacklist

- cookbooks/planet/files/default/replication-bin/replicate-changesets
> Include comment ids in replicate-changesets

- cookbooks/dhcpd/README.md
> fix: README.md missing verb

- cookbooks/dev/README.md
> fix: README.md spelling

- cookbooks/imagery/recipes/au_vic_melbourne_aerial.rb
- roles/imagery.rb
closes https://github.com/openstreetmap/operations/issues/1213
cc @Firefishy
> add city of melbourne imagery

- cookbooks/vectortile/attributes/default.rb
- cookbooks/vectortile/recipes/default.rb
This is preparation for a storage format change
> Switch tilekiln version to attributes

- cookbooks/vectortile/attributes/default.rb
- cookbooks/vectortile/recipes/default.rb
- roles/dribble.rb
I've turned off Dribble on the CDN
> Update tilekiln dribble

- cookbooks/vectortile/recipes/default.rb
- cookbooks/vectortile/templates/default/tiles-rerender.erb
- cookbooks/vectortile/templates/default/vector-update-tile.erb
This should reduce the amount of work that is caused by updates.
> Re-render vector tiles by layer

- roles/chef-repository.rb
- roles/git.rb
Add @pnorman to git and chefrepo groups to allow him to commit his own vectortile changes.
Pro Tip, add the `git.openstreetmap.org` repo to your origin to allow pushing to both remote repos. 
eg:
```
git remote set-url --add --push origin ssh://git.openstreetmap.org/var/lib/git/public/chef.git
```
> Add pnorman to git and chefrepo groups

- cookbooks/vectortile/attributes/default.rb
- cookbooks/vectortile/recipes/default.rb
- cookbooks/vectortile/templates/default/render-lowzoom.erb
- cookbooks/vectortile/templates/default/render-ocean.erb
This is a brute-force approach to updating the coastline. I'm not sure how well it will perform and only consider it an interim solution.
> Re-render ocean layers weekly

- cookbooks/tile/templates/default/export.erb
> Map export: replace cgi by urllib
